#ifndef COMPILER_H
#define COMPILER_H

#include "chunk.h"  // For Bytecode chunk definitions
#include "object.h" // For ObjFunction type

/**
 * Compiles Delirium source code into executable bytecode.
 *
 * @param source Null-terminated string containing Delirium source code
 * @return Pointer to compiled ObjFunction containing the bytecode,
 *         or NULL if compilation fails
 *
 * @note The returned ObjFunction owns all generated bytecode and constants.
 * @note Errors during compilation are reported via stderr output.
 */
ObjFunction* compile(char const* source);

#endif // COMPILER_H