#ifndef MUTATION_CONSTANTS_H
#define MUTATION_CONSTANTS_H

#include <string>
#include <vector>

#include <cmath>
#include <limits>
#include <string>
#include <vector>

static std::vector<std::string> const uselessFuncs = {
    "void doNothing() {}",
    "int alwaysZero() { return 0; }",
    "double piApproximation() { return 3.0; }",
    "bool alwaysTrue() { return true; }",
    "std::string emptyString() { return std::string(); }",
    "char nullChar() { return '\\0'; }",
    "int identity(int x) { volatile int y = x; return y; }",
    "double slightlyDifferent(double d) { return d + std::numeric_limits<double>::epsilon(); }",
    "bool opposite(bool b) { volatile bool not_b = !b; return not_b; }",
    "int addAndSubtract(int a, int b) { return a + b - b; }",
    "std::string commentOnly() { /* This function does nothing. */ return \"\"; }",
    "void unusedVariable() { int unused = 5; }",
    "int convolutedZero() { int x = 10; x = x - 5; x = x - 5; return x; }",
    "double squareRootOfOne() { return std::sqrt(1.0); }",
    "bool compareEqual(int a, int b) { return a == b; }",
    "std::string stringLiteral() { return \"hello\"; }",
    "char someChar() { return 'a'; }",
    "unsigned int maxUnsigned() { return std::numeric_limits<unsigned int>::max(); }",
    "long long minLongLong() { return std::numeric_limits<long long>::min(); }",
    "float halfOfTwo() { return 2.0f / 2.0f; }",
    "void localScope() { { int localVar = 10; } }",
    "int returnArgument(int arg) { return arg; }",
    "double multiplyByOne(double val) { return val * 1.0; }",
    "bool logicalOrTrue(bool val) { return val || true; }",
    "std::string createThenReturn() { std::string s = \"useless\"; return s; }",
    "int bitwiseAndMax(int val) { return val & std::numeric_limits<int>::max(); }",
    "double castToIntThenToDouble(int val) { return static_cast<double>(val); }",
    "bool alwaysFalse() { return false; }",
    "int decrementThenIncrement(int val) { return --val + 1; }",
    "void emptyLoop(int n) { for (int i = 0; i < n; ++i) {} }",
    "int addZero(int x) { return x + 0; }",
    "double subtractZero(double d) { return d - 0.0; }",
    "bool logicalAndSelf(bool b) { return b && b; }",
    "std::string concatenateEmpty(const std::string& s) { return s + \"\"; }",
    "char returnFirstChar(const std::string& s) { if (!s.empty()) return s[0]; return '\\0'; }",
    "int multiplyByOnePointZero(int x) { return static_cast<int>(x * 1.0f); }",
    "double divideByOnePointZero(double d) { return d / 1.0; }",
    "bool compareNotEqual(int a, int b) { return !(a == b); }",
    "std::string createUnusedString() { std::string temp = \"temporary\"; return \"\"; }",
    "int bitwiseOrZero(int val) { return val | 0; }",
    "double noOperation(double val) { volatile double temp = val; return temp; }",
    "bool checkGreaterThanOrEqual(int a, int b) { return a >= b || a < b; }",
    "std::string returnArgumentAsCopy(std::string s) { return s; }",
    "int incrementThenReturnOriginal(int& val) { int original = val; ++val; return original; }",
    "double decrementThenReturnIncremented(double& val) { --val; return val + 1; }",
    "bool checkLessThanOrEqual(int a, int b) { return a <= b || a > b; }",
    "std::string localStringLiteral() { const char* str = \"literal\"; return std::string(str); }",
    "int shiftLeftByZero(int val) { return val << 0; }",
    "double shiftRightByZero(double val) { return static_cast<int>(val) >> 0; }",
    "bool notNot(bool b) { return !!b; }",
    "std::string unusedReturnValue() { return \"ignored\"; }",
    "int convolutedIdentity(int x) { int y; y = x; return y; }",
    "double squareOfOne() { return std::pow(1.0, 2.0); }",
    "bool xorFalse(bool b) { return b ^ false; }",
    "std::string createAndDestroy() { std::string local; return \"\"; }",
    "int moduloMaxInt(int val) { return val % std::numeric_limits<int>::max(); }",
    "double addEpsilonThenSubtract(double val) { return val + std::numeric_limits<double>::epsilon() - std::numeric_limits<double>::epsilon(); }",
    "bool compareSelfEqual(int x) { return x == x; }",
};

static std::string const chars = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ";

static std::vector<std::string> errorMessages = {
    "Oops! The compiler encountered an existential crisis and couldn't process your code. Maybe it’s time for you to reconsider your life choices.",
    "Fatal Error: Compiler found your code so confusing, it now believes it's in a bad relationship.",
    "Unrecoverable Error: This code is more complicated than your last breakup.",
    "Fatal Error: Your code doesn't even deserve an exception.",
    "Oh no! This code is so broken, it’s getting *debugged* by the universe itself.",
    "Compiler can't continue. It's too busy Googling 'How to understand terrible code.'",
    "Critical Failure: Your code has left the compiler in a permanent state of despair.",
    "Error 404: Brain not found. Please re-enable logic to proceed.",
    "Compiler crashed. It couldn't even process your attempt to program. Maybe try drawing a stick figure next time.",
    "System is down: Your code has failed so hard, the compiler filed for unemployment.",
    "Fatal Error: You’ve confused the compiler so much, it now thinks it’s part of a performance art piece.",
    "Internal Compiler Error: Your code is so bad, the compiler wants to be on strike.",
    "Crash detected: Your code was so bad, even the compiler gave up on life.",
    "Oops! Something went wrong… and so did your code. Don't worry, though, you're in good company.",
    "Compiler error: Code so tragic it triggered a system-wide emotional shutdown.",
    "Fatal Error: Your code broke the compiler, and frankly, it's kind of your fault.",
    "System crash: The compiler is not paid enough to deal with your nonsense.",
    "Critical Error: The compiler has thrown in the towel. It’s accepting your code’s resignation.",
    "Oops, crash! Your code’s logic is so twisted, even the compiler needed a stiff drink.",
    "Error: This code has been marked as 'too weird for reality'.",
    "Compiler fail: Please consider applying for a debugging class, stat.",
    "System Failure: The compiler ran out of patience while trying to figure out your mess.",
    "Fatal Error: Your code needs therapy. Maybe you should too.",
    "Compilation aborted. The compiler is in mourning for what you just wrote.",
    "Internal Error: The compiler is in 'please don't make me do this' mode.",
    "Fatal Error: The compiler feels personally attacked by your code.",
    "Error 666: Your code is so evil, it broke the compiler's spirit.",
    "Critical Failure: Even the compiler's dog walked out after seeing this code.",
    "Why do programmers prefer dark mode? Because the light attracts bugs.",
    "Why do Java developers wear glasses? Because they can't C#.",
    "Why was the JavaScript developer sad? Because he didn’t know how to 'null' his feelings.",
    "How many programmers does it take to change a light bulb? None. It’s a hardware problem.",
    "I told my computer I needed a break, and now it won't stop sending me ads for vacation packages.",
    "There are 10 types of people in the world: Those who understand binary and those who don’t.",
    "Why don't programmers like nature? It has too many bugs.",
    "How do you comfort a JavaScript bug? You console it.",
    "Why did the coder go broke? Because he used up all his cache.",
    "I have a joke on programming but it’s only for C++ developers... it’s a bit too complicated.",
    "What’s a programmer's favorite hangout place? The Foo Bar.",
    "To understand what recursion is, you must first understand recursion.",
    "Why do C++ programmers have trouble with relationships? They have too many pointers.",
    "Why was the developer afraid of the server? It had too many connections.",
    "Oops! The compiler fainted after seeing that, and so did we.",
    "System Error: The compiler needed a mental health day after processing your code.",
    "Internal failure: Your code is now a black hole of logic and sanity.",
    "Fatal Error: The compiler filed for divorce after reading your code.",
    "Unrecoverable crash: The compiler needed to take a vacation after reading this mess.",
    "System Crash: This code is so bad, the compiler is now Googling 'how to handle failure'.",
    "Oops, the compiler fainted. Your code is so convoluted, it made even the computer question its purpose in life.",
    "Fatal Error: This code is a trainwreck in slow motion. The compiler is crying.",
    "Error: Your code is so bad, even the error messages need error handling.",
    "Fatal Error: The compiler is questioning whether it was built for this kind of torture.",
    "System Error: The compiler is asking for a raise after processing this disaster.",
    "Oops! Your code is making the compiler question the meaning of existence.",
    "Fatal Error: This code is the compiler’s worst nightmare in pixelated form.",
    "Unrecoverable Error: The compiler tried to debug your code but gave up after a single line.",
    "Fatal Error: This code is more broken than the compiler's will to live.",
    "Crash Detected: The compiler is so confused, it now believes it's a toaster.",
    "Error: The compiler isn't sure if it's crashing or just having an existential crisis.",
    "Oops! The compiler couldn't process this disaster and is now questioning its life choices.",
    "Critical Error: Your code is the compiler’s personal hell.",
    "Fatal Error: The compiler has locked itself in a room to avoid your code.",
    "Oops! Your code was so confusing, even the compiler called for backup.",
    "Fatal Error: The compiler fainted and is currently in the ICU.",
    "Unrecoverable Error: The compiler went on strike after compiling this code.",
    "Internal Error: The compiler is now questioning the point of existence after seeing this.",
    "Oops, crash: The compiler is silently judging your decisions in life.",
    "Critical Failure: Your code is a 404 in the land of logic.",
    "Fatal Error: The compiler refuses to process this code without a bribe.",
    "System Error: The compiler says 'Nope' and refuses to continue.",
    "Fatal Error: The compiler is now seeking legal advice after encountering this code.",
    "Crash Detected: The compiler now has a PhD in 'How to Fail Miserably'.",
    "Oops! This code is so broken, the compiler tried to send it to therapy.",
    "Critical Error: Your code made the compiler consider a career change.",
    "Fatal Error: The compiler says it's too old for this mess.",
    "Oops! Code so complicated, the compiler called in a support group.",
    "Fatal Error: The compiler says, 'I’ve seen enough, thank you very much.'",
    "Critical Error: Your code is too edgy for the compiler to handle.",
    "System Error: The compiler is crying, and so are we.",
    "Internal Compiler Error: Your code is considered a crime in some states.",
    "Fatal Error: The compiler would rather compile your friend’s code, even if they’re a beginner.",
    "Oops! The compiler needs a break after processing this madness.",
    "System Crash: The compiler now identifies as a keyboard, it doesn't want to be part of this anymore.",
    "Fatal Error: Your code is so confusing that the compiler asked for directions.",
    "Critical Failure: The compiler considered taking a vacation after reading this.",
    "Error: Your code made the compiler file for early retirement.",
    "Fatal Error: The compiler is now refusing to acknowledge its existence.",
    "System Failure: The compiler has been emotionally scarred by your code.",
    "Fatal Error: The compiler needs therapy. And you probably do too.",
    "Oops! This code left the compiler questioning the meaning of life.",
    "Error: The compiler needed a glass of wine after trying to understand this.",
    "Fatal Error: Your code was too much for the compiler to handle, it had to take a nap.",
    "Critical Error: The compiler is on strike until you rewrite this mess.",
    "Fatal Error: The compiler saw this code and said, 'Nope. Not today.'",
    "Oops! The compiler's worst nightmare: This code.",
    "Fatal Error: The compiler just asked for a timeout after trying to process your code.",
    "Critical Failure: This code is so broken, the compiler filed for disability.",
    "Unrecoverable Error: The compiler started crying after the first line of your code.",
    "System Error: Your code has caused the compiler to go into 'reactive' mode. Good luck."
};

#endif
